### ISSUE TITLE
Support for generic method?

### ISSUE THREAD

**Issue by bcronje** [HangfireIO/Hangfire#136]
I tried to enqueue a static generic function:

```
 BackgroundJob.Enqueue(() => MyService.DoTask<CustomType>(id);
```

And got the following error:

> Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true

What would be required to enable support for calling generic methods?

**Comment by supergibbs** [comment]
https://github.com/HangfireIO/Hangfire/pull/222

**Comment by DR9885** [comment]
Using version 1.6.6, still seeing a similar issue:
`
BackgroundJob.Enqueue(() => Process<MessageType>(start, end))
`

StackTrace:
   at System.RuntimeType.SanityCheckGenericArguments(RuntimeType[] genericArguments, RuntimeType[] genericParamters)
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   at Hangfire.Common.TypeExtensions.GetNonOpenMatchingMethod(Type type, String name, Type[] parameterTypes)
   at Hangfire.Common.Job.FromExpression(LambdaExpression methodCall, Type explicitType)
   at Hangfire.BackgroundJobClientExtensions.Create(IBackgroundJobClient client, Expression`1 methodCall, IState state)

**Comment by leidegre** [comment]
There is a trivial workaround for this problem and that is to simply move the type parameter up to the class level, like this:

~~~
public static GenericJobMethod<T>() {
  // ...
}

public class JobClass<T>
{
  public static Run() {
    GenericJobMethod<T>();
  }
}

BackgroundJob.Enqueue(() => JobClass<TheJobGenericArgument>.Run());
~~~

**Comment by aidmsu** [comment]
@DR9885 
We fixed this bug only in Hangfire 1.6.7. Update to Hangfire 1.6.7 or later and enqueue all generic methods like this:
```csharp
BackgroundJob.Enqueue(() => Process<MessageType>(start, end))
```

**Comment by twilly86** [comment]
I'm trying to offload heavy processing on a background server (not my main web app)

From what I am seeing, I would need to load in all my assemblies that are required to enqueue the process so that I can pass in that method to the enqueue function.

I'd prefer not to load in all my assemblies that are only needed on the background server onto the web app just to call the function from within enqueue.  

Could you give guidance if I am thinking about this correct, would the Process function help with this or is there an easy way to resolve this by passing a single json object which says which function to call and then my background server picks that up and processes the correct job.

**Comment by gayancc** [comment]
It seems still cannot fire generic method 
https://discuss.hangfire.io/t/system-invalidoperationexception-when-enqueue-generic-method/7288
