### ISSUE TITLE
Constant deadlocks on 1.7.3

### ISSUE THREAD

**Issue by jcvu01** [HangfireIO/Hangfire#1447]
I just updated the hangfire to 1.7.3 from 1.6.20 and now constantly getting deadlocks error. I thought latest version resolved that issue. Is my config incorrect?

```csharp
var options = new SqlServerStorageOptions
{
	CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
	SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
	QueuePollInterval = TimeSpan.FromMilliseconds(100),
	UseRecommendedIsolationLevel = true,
	UsePageLocksOnDequeue = true,
	DisableGlobalLocks = true
};

GlobalConfiguration.Configuration
	.UseSqlServerStorage("conectionstring", options)
	.UseSerilogLogProvider();
```

System.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 1423) was deadlocked on lock resources with another process and has been chosen as the deadlock victim.

Any help?
thanks

Chan

**Comment by odinserj** [comment]
Thanks for reporting this @jcvu01, your settings are good. Could you tell me the output of the following SQL query to understand whether you've already migrated to the newest schema?

```sql
SELECT * FROM [HangFire].[Schema]
```

Also, any deadlock graphs will be useful to understand what queries are being deadlocked. You can use [SQL Profiler](https://docs.microsoft.com/en-us/sql/tools/sql-server-profiler/analyze-deadlocks-with-sql-server-profiler?view=sql-server-2017) to obtain them, [trace flag 1222](https://www.mssqltips.com/sqlservertip/2130/finding-sql-server-deadlocks-using-trace-flag-1222/) or use a [special query](https://blogs.msdn.microsoft.com/azuresqldbsupport/2017/01/21/lesson-learned-19-how-to-obtain-the-deadlocks-of-your-azure-sql-database/) on SQL Azure.

**Comment by jcvu01** [comment]
Schema version is 5

![image](https://user-images.githubusercontent.com/20119877/59356076-23ae9c00-8cf6-11e9-821d-9b8445b243f8.png)

Also, the hangfire job services don't pick up job correctly.
I have 4 servers with 30 jobs each but the processing queue barely has any jobs.
![image](https://user-images.githubusercontent.com/20119877/59356651-4c836100-8cf7-11e9-8a47-d7df3052bd76.png)


thanks,

Chan

**Comment by dlazzarino** [comment]
I have the same situation and the same issue. Fortunately, at the moment, I'm testing it in a test environment.

Below some useful details:
I have updated hangfire to 1.7.3 from 1.6.20. First, I have updated all the packages leaving the
database schema at version 5.  After that, I have upgraded also the database schema to version 7.

My configuration is exactly that described in the [upgrading guide](https://docs.hangfire.io/en/latest/upgrade-guides/upgrading-to-hangfire-1.7.html)

The only part I don't understand (and I have not applied) is:

> Setting BackgroundJobServerOptions.TaskScheduler to null (TaskScheduler.Default is used by default) will force async continuations to be processed by the worker thread itself, reducing the number of required threads (that’s good). But if you are using non-recommended and dangerous Task.Result or Task.GetAwaiter().GetResult() methods, your async background jobs can be deadlocked.

Other info:

- I have about 150 recurring jobs
- The average scheduling time is about every 5/10 minutes 
- My SQL Server Version is 13.0.5026.0

Our DBA traced a lot of Exclusive xp_userlock on hangfire database. I know this is the "locking technique" used by Hangfire but, before the 1.7.3 upgrade, the number of locks/deadlocks was significantly lower. In addition, this situation generates a performance issue on the server.
I have tried to downgrade the hangfire schema from 7 to 5 but the issue remains.

It seems that the new hangfire engine version applies a more aggressive lock approach.
It's an impression, I haven't taken a look at the code yet.  

Let me know if you need additional trace/details. 
Ps. I saw that Chan already provided a deadlock trace and a dashboard screenshot. I confirm I am in the same situation

Thanks in advance,
Diego

**Comment by jcvu01** [comment]
Just give an update about the queue poll. There might be some kind of exclusive access to the queue table that blocks the workers to fetch new jobs.
I downgraded 3 of 4 queue servers to 1.6.20, but still only few jobs being process at a time. When i took out the server that runs on 1.7.3, the job processing instantly jumped to 90.

**Comment by odinserj** [comment]
Chan, you skipped the [Migrating the schema](https://docs.hangfire.io/en/latest/upgrade-guides/upgrading-to-hangfire-1.7.html#migrating-the-schema) section during the upgrade.

@dlazzarino, are you using MySQL as a job storage?

**Comment by jcvu01** [comment]
@odinserj, 
The upgrade doc says 1.7.3 is compatible with Schema 5 and it suggests we dont do migration sometimes later because the database needs to be offline. Is it not the case?

@dlazzarino mentioned he has same issue even after upgrading to schema 7. He is using MS Sql server 13.0 while mine is 12.0.5589.7.

**Comment by dlazzarino** [comment]
@odinserj , as @jcvu01 wrote, I'm using MS Sql Server as a job storage

**Comment by odinserj** [comment]
@jcvu01, thanks. I've updated the [latest section](https://docs.hangfire.io/en/latest/upgrade-guides/upgrading-to-hangfire-1.7.html#updating-configuration) of the upgrade guide to point that Schema 7 is required for `UsePageLocksOnDequeue` and `DisableGlobalLocks`. Please turn them off until you run a migration to avoid deadlocks.

@dlazzarino since you are already on the newest schema version, then everything is different. Please show me your deadlock graphs, configuration logic and rows from the `[HangFire].[Schema]` table to ensure migration was performed.

**Comment by jcvu01** [comment]
@odinserj thanks.
Does using old schema cause the job queue to not process correctly too? 
here is my updated option
var options = new SqlServerStorageOptions
			{
				CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
				SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
				QueuePollInterval = TimeSpan.FromMilliseconds(100)
			};

Queue jobs still don't get pick up correctly and I am on Schema 5.

Thanks

**Comment by odinserj** [comment]
Could you also try to restore previous value for the `QueuePollInterval`?

**Comment by jcvu01** [comment]
I did try the old value which is 1 second and it behaves the same.
On version 1.6.20, the processing queue is always max out (120 jobs for 4 servers) if there are more than 120 jobs in the queued. However, on the latest version, the processing queue never reach 50 and I can see idle time between jobs where the processing queue is 0 for few seconds even there are thousands of jobs in the waiting queue. You can see it the screenshot above that there are over 6k of queue jobs but processing queue is 2

**Comment by odinserj** [comment]
Hm, will try to reproduce the issue tomorrow and release a fix, but I didn't notice this during testing with huge number of jobs. Could you provide any information from SQL Server side to narrow the search? Like query plans, avg/max/cpu/waiting time for the query using [Performance Dashboard](https://docs.microsoft.com/en-us/sql/relational-databases/performance/performance-dashboard) or Brent Ozar's [First Responder Kit](https://www.brentozar.com/first-aid/)?

**Comment by jcvu01** [comment]
@odinserj, unfortunately I already downgraded back  to 1.6.20 so the current dashboard might not be useful. However,  I am using SQL cluster with high resource availability so resources shouldn't be an issue. I will try to update the schema to 7 and try latest version again to see if the issue resolve. 
Can you confirm that schema 7 is compatible with 1.6.20? Downgrading Hangfire version code is easy, but schema downgrade is hard.

**Comment by dlazzarino** [comment]
@odinserj I have updated my configuration putting UsePageLocksOnDequeue and DisableGlobalLocks to false. I'm using Hangfire engine 1.7.3 with Hangfire DB schema 5 on MS SQL Server 13.0.5026.0. I have about 170 recurring jobs with 5-10 minutes as the average scheduling time. 
Immediately, after the deploy with new parameters, all deadlocks disappears. I have monitored it for 24 hours and I have not found any critical issues. Also, queue jobs pick up correctly.   

Next step, I'll try to upgrade database schema to version 7 on the same environment and I'll give you  a feedbak.

Thanks all for support and suggestion

**Comment by odinserj** [comment]
@jcvu01, it's better to use 1.6.23 or later when working with schema 7. But you shouldn't downgrade to 1.6.X if you already set compatibility level to `Version_170` or calling `UseRecommendedSerializerSettings`, because old version doesn't know how to deal with the new data format. 

I've also realized that an exception during the processing that causes background job to be requeued or a long running job *may* cause a deadlock even when `UsePageLocksOnDequeue` and `DisableGlobalLocks` set to `false` due to `TABLE SCAN` operator in those queries. But I wasn't able to reproduce it when using MSSQL 2014 (but they will be fixed nevertheless). 

If you saved deadlock information somewhere, please tell me what queries are involved. Also, if you are using any non-default settings either for server, or database, please let me know.

@dlazzarino, thank you for update. The new settings should work fine with `Schema 7`. If not and you have deadlocks, please let me know.

**Comment by odinserj** [comment]
I've fixed queries mentioned above, and nightly build Hangfire 1.7.3-build-02912 is available on CI feed https://ci.appveyor.com/nuget/hangfire.

**Comment by jcvu01** [comment]
Just give an update.
After updating schema to 7. Everything runs smoothly for a week already, no deadlocks.

Thanks

**Comment by eBenefitsKevin** [comment]
I upgraded the scheme to version 7, but still experiencing the deadlock. The callstack is mentioning the ChangeState method? Anyone?

**Comment by odinserj** [comment]
Please upgrade to 1.7.36 (the latest version in 1.7.X branch) and apply the recommended settings for Hangfire 1.7 as written here - https://docs.hangfire.io/en/latest/configuration/using-sql-server.html#configuration - I haven't heard about any deadlock issues for a long time.

**Comment by eBenefitsKevin** [comment]
We are upgrading to version 8 soon. Will let you know if that fixes our issues. Thanks for the reply
