### ISSUE TITLE
Instance doesn't recover properly if database goes offline

### ISSUE THREAD

**Issue by siada** [HangfireIO/Hangfire#1605]
So for example, a user left a tab open on the Hangfire Recurring Jobs page when the sql server was rebooted overnight (this usually takes 20 minutes or so), the server obviously spews out errors during the time that SQL is offline however once SQL comes back online it's like hangfire has saturated all the available connections in the process? 

I end up with the error:

	System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
	   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
	   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
	   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
	   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
	   at System.Data.SqlClient.SqlConnection.Open()
	   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
	   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
	   at Hangfire.SqlServer.SqlServerMonitoringApi.GetStatistics()
	   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
	   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
	   at System.Lazy`1.CreateValue()
	   at Hangfire.Dashboard.DashboardMetrics.<>c.<.cctor>b__1_0(RazorPage page)
	   at Hangfire.Dashboard.JsonStats.Dispatch(DashboardContext context)
	   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
	   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
	   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
	   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
	   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
	   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

And it is only fixed by stopping and restarting the dotnet process

I am using hangfire v 1.7.1, with the following SqlServerStorageOptions

	new SqlServerStorageOptions
	{
		CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
		SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
		QueuePollInterval = TimeSpan.Zero,
		UseRecommendedIsolationLevel = true,
		UsePageLocksOnDequeue = true,
		DisableGlobalLocks = true,
	}

**Comment by odinserj** [comment]
Thank you for the report @siada! This problem was already fixed, please see the referenced issue, and the change will be available in version 1.7.9 next Monday. Meanwhile you can use version `1.7.8-build-03079` from the CI feed `https://ci.appveyor.com/nuget/hangfire` or download binaries from the [Artifacts page](https://ci.appveyor.com/project/odinserj/hangfire-525/builds/30076958/artifacts).

Duplicates #1602.

**Comment by siada** [comment]
Ah OK, thanks for the for the quick response @odinserj ! It's not a massively pressing issue for us as SQL doesn't go down often, I'll wait for the 1.7.9 release and try it out

**Comment by siada** [comment]
@odinserj looks like I'm still getting the same problem on 1.7.9, the CPU gets maxed out on the process and the logs just spam this until the process is restarted:

    fail: Hangfire.Processing.BackgroundExecution[0]
          Execution BackgroundServerProcess is still in the Failed state for 05:07:09.6563630 due to an exception, will be retried no more than in 00:00:15
    System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
       at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
       at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
       at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
       at System.Data.SqlClient.SqlConnection.Open()
       at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
       at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
       at Hangfire.SqlServer.SqlServerStorage.UseConnection(DbConnection dedicatedConnection, Action`1 action)
       at Hangfire.Server.BackgroundServerProcess.CreateServer(BackgroundServerContext context)
       at Hangfire.Server.BackgroundServerProcess.Execute(Guid executionId, BackgroundExecution execution, CancellationToken stoppingToken, CancellationToken stoppedToken, CancellationToken shutdownToken)
       at Hangfire.Server.BackgroundProcessingServer.RunServer(Guid executionId, Object state)
       at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)

**Comment by MPieter** [comment]
I am experiencing a similar issue. @siada what's the workaround you are currently using ?

**Comment by tjipz8** [comment]
I'm having similar issue "Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached."

it keep logs that every 5 minute, and stop when the restarting the process

**Comment by caruizse** [comment]
HI Team, I have same issue with version 1.7.25, SQL instance is disconnected and can't reconnect again until HangFire server is restarted

**Comment by odinserj** [comment]
Please try to reference [`System.Data.SqlClient`](https://www.nuget.org/packages/System.Data.SqlClient/) of the latest version explicitly in your project (currently it's 4.8.3) – exception happens inside `SqlConnection` class, and Hangfire uses it the same way as a regular application.
